let BattleImages = {
    Battle_Cup_Bidoof: "/resource/image/Battle/Battle_Cup_Bidoof.png",
    Battle_Cup_Catch: "/resource/image/Battle/Battle_Cup_Catch.png",
    Battle_Cup_Catch_GO_Fest_2022: "/resource/image/Battle/Battle_Cup_Catch_GO_Fest_2022.png",
    Battle_Cup_Color: "/resource/image/Battle/Battle_Cup_Color.png",
    Battle_Cup_Electric: "/resource/image/Battle/Battle_Cup_Electric.png",
    Battle_Cup_Element: "/resource/image/Battle/Battle_Cup_Element.png",
    Battle_Cup_Element_Remix: "/resource/image/Battle/Battle_Cup_Element_Remix.png",
    Battle_Cup_Evolution: "/resource/image/Battle/Battle_Cup_Evolution.png",
    Battle_Cup_Fantasy: "/resource/image/Battle/Battle_Cup_Fantasy.png",
    Battle_Cup_Fighting: "/resource/image/Battle/Battle_Cup_Fighting.png",
    Battle_Cup_Fighting_Remix: "/resource/image/Battle/Battle_Cup_Fighting_Remix.png",
    Battle_Cup_Fossil: "/resource/image/Battle/Battle_Cup_Fossil.png",
    Battle_Cup_Galar: "/resource/image/Battle/Battle_Cup_Galar.png",
    Battle_Cup_Halloween: "/resource/image/Battle/Battle_Cup_Halloween.png",
    Battle_Cup_Hisui: "/resource/image/Battle/Battle_Cup_Hisui.png",
    Battle_Cup_Hoenn: "/resource/image/Battle/Battle_Cup_Hoenn.png",
    Battle_Cup_Holiday: "/resource/image/Battle/Battle_Cup_Holiday.png",
    Battle_Cup_Johto: "/resource/image/Battle/Battle_Cup_Johto.png",
    Battle_Cup_Jungle: "/resource/image/Battle/Battle_Cup_Jungle.png",
    Battle_Cup_Jungle_Remix: "/resource/image/Battle/Battle_Cup_Jungle_Remix.png",
    Battle_Cup_Kanto: "/resource/image/Battle/Battle_Cup_Kanto.png",
    Battle_Cup_Little: "/resource/image/Battle/Battle_Cup_Little.png",
    Battle_Cup_Little_Remix: "/resource/image/Battle/Battle_Cup_Little_Remix.png",
    Battle_Cup_Love: "/resource/image/Battle/Battle_Cup_Love.png",
    Battle_Cup_Mountain: "/resource/image/Battle/Battle_Cup_Mountain.png",
    Battle_Cup_Psychic: "/resource/image/Battle/Battle_Cup_Psychic.png",
    Battle_Cup_Retro: "/resource/image/Battle/Battle_Cup_Retro.png",
    Battle_Cup_Singletype: "/resource/image/Battle/Battle_Cup_Singletype.png",
    Battle_Cup_Spring: "/resource/image/Battle/Battle_Cup_Spring.png",
    Battle_Cup_Summer: "/resource/image/Battle/Battle_Cup_Summer.png",
    Battle_Cup_Sunshine: "/resource/image/Battle/Battle_Cup_Sunshine.png",
    Battle_Cup_Weather: "/resource/image/Battle/Battle_Cup_Weather.png",
    Battle_Cup_Willpower: "/resource/image/Battle/Battle_Cup_Willpower.png",
    Battle_League_Great: "/resource/image/Battle/Battle_League_Great.png",
    Battle_League_Great_Remix: "/resource/image/Battle/Battle_League_Great_Remix.png",
    Battle_League_Master: "/resource/image/Battle/Battle_League_Master.png",
    Battle_League_Ultra: "/resource/image/Battle/Battle_League_Ultra.png",
    Battle_League_Ultra_Remix: "/resource/image/Battle/Battle_League_Ultra_Remix.png",
    Flying: "/resource/image/Battle/Flying.png",
    GO_Tour_Logo: "/resource/image/Battle/GO_Tour_Logo.png",
    Premier_Ball: "/resource/image/Battle/Premier_Ball.png",
};

export default BattleImages;
